### ISSUE TITLE
`kbd` element is unreadable

### ISSUE THREAD

**Issue by dbohdan** [ChimeraCSS/ChimeraCSS#31]
I tried rendering a [test file](https://paste.dbohdan.com/temp.1694108247.html) with light-mode ChimeraCSS in Firefox 117.0 and Chromium 115.0.5790.170 on desktop Linux and found that the contents of `<kbd>` was not readable.

# Screenshot 

![chimeracss](https://github.com/ChimeraCSS/ChimeraCSS/assets/3179832/1d7a9fba-00cf-4ec0-9654-261453e2290a)

**Comment by J0hans1** [comment]
Hello!

Thank you for reporting this bug. As of version 1.1.3 ChimeraCSS wont pursue darkmode for the forseeable future to make the framework as lightweight and easy-to-use/learn as possible. 

The bug was a result of a missing comma, while ussing comma separated selectors in the CSS.

Anyway all darkmode code is purged and the <kbd> element works as intended

![image](https://github.com/ChimeraCSS/ChimeraCSS/assets/90006516/92b72f11-6934-4738-8147-534cc612bade)
